-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 12:54:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bookingappdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bookingappdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bookingappdb` DEFAULT CHARACTER SET utf8 ;
USE `bookingappdb` ;

-- -----------------------------------------------------
-- Table `bookingappdb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookingappdb`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `usertype` INT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookingappdb`.`Booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookingappdb`.`booking` (
  `booking_id` INT NOT NULL AUTO_INCREMENT,
  `passenger_id` INT NOT NULL,
  `route_id` INT NOT NULL,
  `quantity` INT NULL,
  `date_time` DATETIME NOT NULL,
  `total_price` FLOAT NOT NULL,
  `transaction_id` INT NULL,
  PRIMARY KEY (`booking_id`),
  UNIQUE INDEX `booking_id_UNIQUE` (`booking_id` ASC) VISIBLE,
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookingappdb`.`TransactionRecord`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookingappdb`.`transactionrecord` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `amount` FLOAT NOT NULL,
  `date_of_payment` DATETIME NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`transaction_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookingappdb`.`Route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookingappdb`.`route` (
  `route_id` INT NOT NULL AUTO_INCREMENT,
  `start_station` VARCHAR(45) NOT NULL,
  `end_station` VARCHAR(45) NOT NULL,
  `date_time` DATETIME NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`route_id`),
  UNIQUE INDEX `route_id_UNIQUE` (`route_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bookingappdb`.`Discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bookingappdb`.`discount` (
  `discount_id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(45) NOT NULL,
  `route_id` INT NOT NULL,
  `discount_percent` DOUBLE NOT NULL,
  PRIMARY KEY (`discount_id`),
  UNIQUE INDEX `discount_id_UNIQUE` (`discount_id` ASC) VISIBLE,
  UNIQUE INDEX `code_UNIQUE` (`code` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
